class Replies:
    SUPORTE     = ('🦖  Em qual sistema você gostaria de atendimento?\n  1 - Folha_Win\n  2 - Fiscal_New\n  3 - Contabil\n  4 - Nfe\n  5 - Outro (Recibos, caixa, nfe...)')
    FINANCEIRO  = ('🦖  Deseja gerar o boleto?\n\n https://gerasoft.com.br/')
    ORCAMENTO   = ('🦖  Pega os dados do usuario para entrarmos em contato\n\n https://gerasoft.com.br/fale-conosco')
    TUTORIAL    = ('🛠  Em construção...')
    DEFAULT     = ('🦖  Olá, sou o Geraldino, em que posso te ajudar hoje?\n  1- Suporte\n  2- Financeiro\n  3- Orçamento\n  4- Tutoriais')
    SUP_NOME    = ('🦖  Informe seu nome:')
    SUP_NUMERO  = ('🦖  Informe seu número para contato:')
    SUP_EMPRESA = ('🦖  Informe a empresa que vc trabalha:')
    SUP_DESC    = ('🦖  Relate seu problema (em uma única mensagem):')
    SUP_FIM     = ('\n🦖  Nossos profissionais entrarão em contato!')            